/**
 * Build-time helpers for the PDF Lab service worker.
 *
 * Pure functions (no Vite dependency) so they can be unit-tested directly:
 *   - createPrecacheInventory(): walks a build output directory and returns a
 *     deterministic, content-hashed list of every shipped file.
 *   - renderServiceWorker(): injects that inventory into the worker template.
 *   - finalizeManifest(): gives the web app manifest a stable `id` that matches
 *     Vite's configured base path.
 */
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync } from 'node:fs'
import path from 'node:path'

export const SERVICE_WORKER_FILE = 'sw.js'
export const BUILD_PLACEHOLDER = '__PDF_LAB_BUILD__'

/** Vite emits hashed, immutable assets as `name-XXXXXXXX.ext` inside assets/. */
const IMMUTABLE_ASSET = /^assets\/.+-[A-Za-z0-9_-]{8}\.[a-z0-9]+$/

const DEFAULT_EXCLUDES = [
  (relative) => relative === SERVICE_WORKER_FILE,
  (relative) => relative.endsWith('.map'),
  (relative) => relative.split('/').some((segment) => segment.startsWith('.')),
]

export function sha256(buffer) {
  return createHash('sha256').update(buffer).digest('hex')
}

function walk(dir, base = '') {
  const files = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const relative = base ? `${base}/${entry.name}` : entry.name
    const absolute = path.join(dir, entry.name)
    if (entry.isDirectory()) files.push(...walk(absolute, relative))
    else if (entry.isFile()) files.push(relative)
  }
  return files
}

/**
 * Lists every file below `outDir` (except the worker itself, source maps and
 * dot files) with its SHA-256 hash. Entries are sorted by URL so the result —
 * and therefore the release version — depends only on file contents.
 *
 * @param {string} outDir absolute path of the build output directory
 * @param {{ exclude?: Array<(relativePath: string) => boolean> }} [options]
 */
export function createPrecacheInventory(outDir, options = {}) {
  if (!statSync(outDir, { throwIfNoEntry: false })?.isDirectory()) {
    throw new Error(`Precache inventory: output directory not found: ${outDir}`)
  }
  const excludes = [...DEFAULT_EXCLUDES, ...(options.exclude || [])]
  const entries = walk(outDir)
    .filter((relative) => !excludes.some((rule) => rule(relative)))
    .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
    .map((relative) => {
      const buffer = readFileSync(path.join(outDir, relative))
      return {
        url: relative.split('/').map(encodeURIComponent).join('/'),
        hash: sha256(buffer),
        size: buffer.byteLength,
        immutable: IMMUTABLE_ASSET.test(relative),
      }
    })
  if (!entries.some((entry) => entry.url === 'index.html')) {
    throw new Error('Precache inventory: index.html is missing from the build output')
  }
  return { version: inventoryVersion(entries), entries }
}

/** Release version: a digest of every precached path and its content hash. */
export function inventoryVersion(entries) {
  return sha256(entries.map((entry) => `${entry.url}\u0000${entry.hash}`).join('\n')).slice(0, 16)
}

/**
 * Produces the deployable worker script from the template.
 * The injected BUILD object is plain JSON: no timestamps, so two builds of the
 * same sources yield byte-identical workers.
 */
export function renderServiceWorker(template, inventory) {
  const occurrences = template.split(BUILD_PLACEHOLDER).length - 1
  if (occurrences !== 1) {
    throw new Error(`Service worker template must contain ${BUILD_PLACEHOLDER} exactly once (found ${occurrences})`)
  }
  const build = {
    version: inventory.version,
    precache: inventory.entries.map(({ url, hash, immutable }) => ({ url, hash, immutable })),
  }
  const banner = [
    '/* PDF Lab service worker — GENERATED by `vite build` from pwa/sw.template.js.',
    ' * Deploy this file (dist/sw.js) together with the rest of dist/. Do not deploy',
    ' * or hand-edit the template: it has no precache inventory and cannot work offline.',
    ` * Release version: ${inventory.version} (${inventory.entries.length} precached files). */`,
    '',
  ].join('\n')
  return banner + template.replace(BUILD_PLACEHOLDER, JSON.stringify(build))
}

/**
 * Returns the manifest with an `id` derived from Vite's base path.
 *
 * `id` is resolved against the origin of start_url (not against the manifest
 * URL), so it must be an absolute path. Root hosting keeps the identity the
 * app always had (`/`, previously implied by start_url). For relative bases
 * ("./") the deploy path is unknown at build time; the member is omitted so
 * browsers fall back to the resolved start_url.
 */
export function finalizeManifest(manifest, base) {
  const next = { ...manifest }
  const normalized = normalizeBasePath(base)
  if (normalized) next.id = normalized
  else delete next.id
  return next
}

/** "/", "/lab/" → same; "./", "" or full URLs → null (unknown absolute path). */
export function normalizeBasePath(base) {
  if (typeof base !== 'string' || !base.startsWith('/') || base.startsWith('//')) return null
  return base.endsWith('/') ? base : `${base}/`
}
