import { test, expect } from '@playwright/test'

async function open(page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Markdown to PDF', exact: true }).click()
}
async function upload(page, markdown) {
  await page.getByLabel('Upload Markdown file').setInputFiles({ name: 'Complete Notes.md', mimeType: 'text/markdown', buffer: Buffer.from(markdown) })
  await expect(page.getByRole('button', { name: 'Export preview PDF', exact: true })).toBeEnabled()
}

test('preflight automatically reports normal imported notes and follows edits and profiles', async ({ page }) => {
  await open(page)
  await upload(page, '# संविधान\n\n## Rights\n\nHello हिंदी 123.\n\n> [!TIP] Recall\n> Read this.\n\n| A | B |\n|---|---|\n| 1 | 2 |\n\n$x^2$\n\n- [ ] Review\n\n```js\nconst x = 1\n```')
  const panel = page.getByRole('region', { name: 'Document preflight' })
  await expect(panel).toHaveAttribute('aria-busy', 'false')
  await expect(panel).toContainText('2 headings (H1: 1 · H2: 1 · H3: 0)')
  await expect(panel).toContainText('1 tables · 0 images · 1 callouts')
  await expect(panel).toContainText('1 math expressions · 1 code blocks · 1 checklist items')
  await expect(panel).toContainText('0 errors · 0 warnings')
  await expect(panel).toContainText('Estimated PDF: ~')
  const stats = await panel.locator('.md-preflight-stats').innerText()
  await page.getByRole('radio', { name: 'Revision', exact: true }).check()
  await expect(panel).toContainText('Revision / A4 content estimate, not pagination')
  expect(await panel.locator('.md-preflight-stats').innerText()).toBe(stats)
  await page.locator('#notes-paper').selectOption('Letter')
  await expect(panel).toContainText('Revision / Letter')
  await page.getByLabel('Edit Markdown').fill('# Fresh\n\n## Topic\n\n### Detail\n\n#### More')
  await expect(panel).toContainText('4 headings')
  await expect(panel).toHaveAttribute('aria-busy', 'false')
  await page.getByLabel('Edit Markdown').fill('')
  await expect(panel).toContainText('Add notes to run preflight')
  await expect(page.getByRole('button', { name: 'Export preview PDF', exact: true })).toBeDisabled()
})

test('missing images, unresolved references, hierarchy and math warnings inform without blocking export', async ({ page }) => {
  await open(page)
  await upload(page, '# Main\n\n#### Jump\n\n![[missing.png]]\n\n![Secret](../../private/secret.png)\n\n[[Other|Alias]] [[#Missing]] [[#^absent]] ![[Other.md]]\n\n$\\notacommand{x}$')
  const panel = page.getByRole('region', { name: 'Document preflight' })
  await panel.locator('summary').click()
  await expect(panel).toContainText('2 image(s) could not be resolved')
  await expect(panel).toContainText('missing.png')
  await expect(panel).not.toContainText('private/secret')
  await expect(panel).toContainText('cross-note Wikilink(s) could not be resolved')
  await expect(panel).toContainText('internal heading link(s) could not be resolved')
  await expect(panel).toContainText('block reference(s) could not be resolved')
  await expect(panel).toContainText('H1 → H4')
  await expect(panel).toContainText('math expression(s) failed KaTeX')
  await expect(page.getByRole('button', { name: 'Export PDF', exact: true })).toBeEnabled()
  await page.locator('iframe').evaluate((frame) => { frame.contentWindow.print = () => { window.__preflightPrint = true } })
  await page.getByRole('button', { name: 'Export preview PDF', exact: true }).click()
  expect(await page.evaluate(() => window.__preflightPrint)).toBe(true)
  await expect(page.getByRole('status')).toContainText('Print dialog requested')
  await page.getByLabel('Edit Markdown').fill('# Clean\n\nNotes')
  await expect(panel).toContainText('0 errors · 0 warnings · 0 info checks')
})

test('supplying assets refreshes missing-image checks; rejected uploads remain non-destructive', async ({ page }) => {
  await open(page)
  await upload(page, '# Note\n\n![[pixel.png]]')
  const panel = page.getByRole('region', { name: 'Document preflight' })
  await expect(panel).toContainText('1 warnings')
  await page.getByLabel('Add image files', { exact: true }).setInputFiles({ name: 'pixel.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64') })
  await expect(panel).toContainText('0 errors · 0 warnings')
  await page.getByLabel('Upload Markdown file').setInputFiles({ name: 'too-large.md', mimeType: 'text/markdown', buffer: Buffer.alloc(5 * 1024 * 1024 + 1, 32) })
  await expect(page.getByRole('alert')).toContainText('too large')
  await expect(page.getByLabel('Edit Markdown')).toHaveValue('# Note\n\n![[pixel.png]]')
  await expect(panel).toContainText('1 headings')
})
