import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import vm from 'node:vm'
import {
  BUILD_PLACEHOLDER,
  createPrecacheInventory,
  finalizeManifest,
  normalizeBasePath,
  renderServiceWorker,
  sha256,
} from '../pwa/precache.js'
import { TEMPLATE_PATH } from '../pwa/vitePlugin.js'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

function fixtureDist(extra = {}) {
  const dir = mkdtempSync(path.join(tmpdir(), 'pdf-lab-dist-'))
  mkdirSync(path.join(dir, 'assets'))
  mkdirSync(path.join(dir, 'icons'))
  mkdirSync(path.join(dir, '.vite'))
  const files = {
    'index.html': '<!doctype html><script src="/assets/index-AbCdEf12.js"></script>',
    'assets/index-AbCdEf12.js': 'console.log("app")',
    'assets/index-AbCdEf12.js.map': '{}',
    'assets/KaTeX_Main-Regular-B22Nviop.woff2': 'font-bytes',
    'icons/icon-192.png': 'png-bytes',
    'manifest.json': '{"name":"x"}',
    'sw.js': 'stale worker from a previous build',
    '.vite/manifest.json': '{}',
    ...extra,
  }
  for (const [file, content] of Object.entries(files)) writeFileSync(path.join(dir, file), content)
  return dir
}

test('inventory lists every shipped file except the worker, source maps and dot files, sorted deterministically', () => {
  const dir = fixtureDist()
  try {
    const inventory = createPrecacheInventory(dir)
    assert.deepEqual(inventory.entries.map((entry) => entry.url), [
      'assets/KaTeX_Main-Regular-B22Nviop.woff2',
      'assets/index-AbCdEf12.js',
      'icons/icon-192.png',
      'index.html',
      'manifest.json',
    ])
    const js = inventory.entries.find((entry) => entry.url === 'assets/index-AbCdEf12.js')
    assert.equal(js.hash, sha256(Buffer.from('console.log("app")')))
    assert.equal(js.immutable, true, 'hashed Vite assets are immutable')
    assert.equal(inventory.entries.find((entry) => entry.url === 'index.html').immutable, false)
    assert.equal(inventory.entries.find((entry) => entry.url === 'icons/icon-192.png').immutable, false)
    assert.match(inventory.version, /^[0-9a-f]{16}$/)
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})

test('the release version changes with any file content and is otherwise stable', () => {
  const a = fixtureDist()
  const b = fixtureDist()
  const c = fixtureDist({ 'icons/icon-192.png': 'different png bytes' })
  const d = fixtureDist({ 'extra.txt': 'a new file' })
  try {
    const first = createPrecacheInventory(a)
    assert.equal(createPrecacheInventory(a).version, first.version, 'same directory twice')
    assert.equal(createPrecacheInventory(b).version, first.version, 'identical content elsewhere')
    assert.notEqual(createPrecacheInventory(c).version, first.version, 'one changed byte changes the release')
    assert.notEqual(createPrecacheInventory(d).version, first.version, 'an added file changes the release')
    // The stale worker or a source map must not influence the version.
    writeFileSync(path.join(a, 'sw.js'), 'another stale worker')
    writeFileSync(path.join(a, 'assets/index-AbCdEf12.js.map'), '{"v":2}')
    assert.equal(createPrecacheInventory(a).version, first.version)
  } finally {
    for (const dir of [a, b, c, d]) rmSync(dir, { recursive: true, force: true })
  }
})

test('inventory refuses a build output without index.html', () => {
  const dir = mkdtempSync(path.join(tmpdir(), 'pdf-lab-empty-'))
  try {
    writeFileSync(path.join(dir, 'manifest.json'), '{}')
    assert.throws(() => createPrecacheInventory(dir), /index\.html is missing/)
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})

test('renderServiceWorker injects the inventory exactly once and stays byte-identical across runs', () => {
  const template = readFileSync(TEMPLATE_PATH, 'utf8')
  const inventory = { version: 'abcdef0123456789', entries: [{ url: 'index.html', hash: 'h1', size: 1, immutable: false }] }
  const worker = renderServiceWorker(template, inventory)
  assert.equal(worker, renderServiceWorker(template, inventory))
  assert.ok(!worker.includes(BUILD_PLACEHOLDER))
  assert.match(worker, /GENERATED by `vite build`/)
  assert.match(worker, /const BUILD = \{"version":"abcdef0123456789","precache":\[\{"url":"index\.html","hash":"h1","immutable":false\}\]\}/)
  assert.throws(() => renderServiceWorker('no placeholder here', inventory), /exactly once/)
  assert.throws(() => renderServiceWorker(`${BUILD_PLACEHOLDER} ${BUILD_PLACEHOLDER}`, inventory), /exactly once/)
})

test('manifest id follows an absolute base path and is omitted for relative bases', () => {
  const manifest = { id: '/', name: 'PDF Lab', start_url: './', scope: './' }
  assert.equal(finalizeManifest(manifest, '/').id, '/')
  assert.equal(finalizeManifest(manifest, '/lab/').id, '/lab/')
  assert.equal(finalizeManifest(manifest, '/lab').id, '/lab/')
  assert.equal('id' in finalizeManifest(manifest, './'), false)
  assert.equal('id' in finalizeManifest(manifest, 'https://cdn.example.com/app/'), false)
  assert.equal(normalizeBasePath('//evil.example/'), null)
  // Relative start_url/scope are untouched: they resolve against the manifest URL.
  assert.equal(finalizeManifest(manifest, '/lab/').start_url, './')
})

function walk(dir, base = '') {
  return readdirSync(dir).flatMap((name) => {
    const relative = base ? `${base}/${name}` : name
    return statSync(path.join(dir, name)).isDirectory() ? walk(path.join(dir, name), relative) : [relative]
  })
}

test('a real `vite build` with a subdirectory base emits a complete, self-consistent worker and manifest', async () => {
  const { build: viteBuild } = await import('vite')
  const outDir = mkdtempSync(path.join(tmpdir(), 'pdf-lab-build-'))
  try {
    await viteBuild({
      root,
      base: '/lab/',
      logLevel: 'silent',
      configFile: path.join(root, 'vite.config.js'),
      build: { outDir, emptyOutDir: true },
    })
    const files = walk(outDir).sort()
    assert.ok(files.includes('sw.js'), 'worker generated')
    const worker = readFileSync(path.join(outDir, 'sw.js'), 'utf8')
    const build = JSON.parse(worker.match(/const BUILD = (\{.*\})\n/)[1])
    const precached = build.precache.map((entry) => decodeURIComponent(entry.url)).sort()
    assert.deepEqual(precached, files.filter((file) => file !== 'sw.js' && !file.endsWith('.map')))

    // Every entry hash matches the shipped bytes, including lazy Markdown chunk and math fonts.
    for (const entry of build.precache) {
      assert.equal(entry.hash, sha256(readFileSync(path.join(outDir, decodeURIComponent(entry.url)))), entry.url)
    }
    assert.ok(precached.some((file) => /^assets\/MarkdownConverter-.*\.js$/.test(file)), 'lazy Markdown module precached')
    assert.ok(precached.some((file) => /^assets\/KaTeX_Main-Regular-.*\.woff2$/.test(file)), 'KaTeX fonts precached')
    assert.ok(precached.includes('manifest.json') && precached.includes('index.html'))
    assert.ok(precached.includes('icons/icon-512-maskable.png') && precached.includes('icons/apple-touch-icon.png'))
    assert.equal(build.version, createPrecacheInventory(outDir).version)

    const manifest = JSON.parse(readFileSync(path.join(outDir, 'manifest.json'), 'utf8'))
    assert.equal(manifest.id, '/lab/')
    assert.equal(manifest.start_url, './')
    for (const icon of manifest.icons) assert.ok(files.includes(icon.src), `${icon.src} shipped`)

    const html = readFileSync(path.join(outDir, 'index.html'), 'utf8')
    assert.match(html, /href="\/lab\/manifest\.json"/)
    assert.match(html, /href="\/lab\/icons\/apple-touch-icon\.png"/)
    assert.match(html, /src="\/lab\/assets\/index-[^"]+\.js"/)
    assert.doesNotMatch(html, /href="\/manifest\.json"/)

    // The worker evaluates standalone and resolves inventory URLs against its own location.
    const context = { self: { registration: { scope: 'https://pdf.test/lab/' }, location: new URL('https://pdf.test/lab/sw.js'), addEventListener() {} }, URL, Map, console }
    context.self.location.href = 'https://pdf.test/lab/sw.js'
    vm.runInNewContext(`${worker}\n;self.__probe = { CACHE_NAME, first: PRECACHE[0].url, shell: SHELL_URL }`, context)
    assert.equal(context.self.__probe.CACHE_NAME, `pdf-lab::/lab/::${build.version}`)
    assert.match(context.self.__probe.first, /^https:\/\/pdf\.test\/lab\/assets\//)
    assert.equal(context.self.__probe.shell, 'https://pdf.test/lab/index.html')
  } finally {
    rmSync(outDir, { recursive: true, force: true })
  }
})
